"""Familles Open Food Facts (`pnns_groups_2`) proposées dans l'app, avec libellé français."""

CATEGORY_LABELS: dict[str, str] = {
    "Meat": "Viande",
    "Processed meat": "Charcuterie",
    "Fish and seafood": "Poisson et fruits de mer",
    "Eggs": "Œufs",
    "Milk and yogurt": "Lait et yaourts",
    "Dairy desserts": "Desserts lactés",
    "Cheese": "Fromages",
    "Plant-based milk substitutes": "Boissons végétales",
    "Legumes": "Légumineuses",
    "Nuts": "Fruits à coque",
    "Fruits": "Fruits",
    "Dried fruits": "Fruits secs",
    "Vegetables": "Légumes",
    "Potatoes": "Pommes de terre",
    "Cereals": "Céréales et féculents",
    "Bread": "Pain",
    "Breakfast cereals": "Céréales du petit-déjeuner",
    "Biscuits and cakes": "Biscuits et gâteaux",
    "Pastries": "Viennoiseries",
    "Sweets": "Confiseries et pâtes à tartiner",
    "Chocolate products": "Chocolat",
    "Ice cream": "Glaces",
    "Pizza pies and quiches": "Pizzas, tartes et quiches",
    "One-dish meals": "Plats préparés",
    "Sandwiches": "Sandwichs",
    "Soups": "Soupes",
    "Appetizers": "Apéritifs",
    "Salty and fatty products": "Produits salés et gras",
    "Dressings and sauces": "Sauces et condiments",
    "Fats": "Matières grasses",
    "Fruit juices": "Jus de fruits",
    "Fruit nectars": "Nectars",
    "Sweetened beverages": "Boissons sucrées",
    "Artificially sweetened beverages": "Boissons édulcorées",
    "Unsweetened beverages": "Boissons non sucrées",
    "Waters and flavored waters": "Eaux",
    "Teas and herbal teas and coffees": "Thés, infusions et cafés",
}
